### ISSUE TITLE
does nothing with firebug 1.11.1

### ISSUE THREAD

**Issue by gcb** [benmmurphy/jsdeminifier_xpi#11]
using the latest firebug 1.11.1, firefox 17.0.1, js deminifier 1.0.7

without any other firebug extensions, does nothing.
my js errors open up the script tag with .js files with their usual one line.

If I have FireRainbow1.5 (firebug syntax highlight) enabled, it will also show a random file under the one line on the script tab. no clue if related. So line 1 of "somefile.js" will be the one line of the file... line 2 will be <html>... and continue with all the contents of "some_other_file.html" for example.

I just installed this and never used before, so forgive i'm doing something dumb. my quick search said it should work without any extra configs.

**Comment by benmmurphy** [comment]
thanks for the bug report.

what web page are you having trouble with?

could you try https://www.google.co.uk/ and see if it works?

**Comment by claudenobs** [comment]
Does work for me (firefox 21a1, firebug 1.11.1, deminifier 1.0.7), works fine with adblock plus, stylish & scriptish

**Comment by gcb** [comment]
yep, i was doing something dumb... took a screen shot, and when i was going to clear the private info out of the image, i noticed the extension adds a button to the status bar.

So i just had to turn it ON.... embarrassing.

**Comment by benmmurphy** [comment]
unfortunately, lots of people seem to have this problem :( i think the UI needs some work

**Comment by claudenobs** [comment]
yep, adding a toolbar button instead would be much preferred (i normally don't use the addonbar)
