### ISSUE TITLE
Add to Tools menu

### ISSUE THREAD

**Issue by barelyfitz** [benmmurphy/jsdeminifier_xpi#6]
Excellent add-on!  Since the Add-on Bar can be hidden (and most of my fellow developers seem to keep it hidden), would it be possible to put an on/off control into the Tools > Web Developer menu?

**Comment by benmmurphy** [comment]
this is a good idea and really easy to implement :) i'll try and do it in the next couple of days. it takes a week or so before it gets reviewed by addons.mozilla.org.

**Comment by benmmurphy** [comment]
i've made the change and submitted a new version to addons.mozilla.org.

if you are desperate to use the new version i have it available here:

https://github.com/downloads/benmmurphy/jsdeminifier_xpi/jsdeminifier_1.0.7.xpi

**Comment by barelyfitz** [comment]
Thanks!
